name: Check for lint errors

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Spell check
        run: yarn run spell-check
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
