name: Update SDK References
on:
  repository_dispatch:
    types: [update_sdk_references]

jobs:
  update_references:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Update Golang reference
        uses: ./.github/actions/update_reference
        with:
          version: ${{ github.event.client_payload.version }}
          dest: docs/sdks/golang/reference
          artifact: bloock_lib_go-docs-${{ github.event.client_payload.version }}.zip
          post_script: scripts/generate-golang-docs.js
      - name: Update Java reference
        uses: ./.github/actions/update_reference
        with:
          version: ${{ github.event.client_payload.version }}
          dest: docs/sdks/java/reference
          artifact: bloock_lib_java-docs-${{ github.event.client_payload.version }}.zip
          post_script: scripts/generate-java-docs.js
      - name: Update Javascript reference
        uses: ./.github/actions/update_reference
        with:
          version: ${{ github.event.client_payload.version }}
          dest: docs/sdks/javascript/reference
          artifact: bloock_lib_js-docs-${{ github.event.client_payload.version }}.zip
          post_script: scripts/generate-js-docs.js
      - name: Update PHP reference
        uses: ./.github/actions/update_reference
        with:
          version: ${{ github.event.client_payload.version }}
          dest: docs/sdks/php/reference
          artifact: bloock_lib_php-docs-${{ github.event.client_payload.version }}.zip
          post_script: scripts/generate-php-docs.js
      - name: Update Python reference
        uses: ./.github/actions/update_reference
        with:
          version: ${{ github.event.client_payload.version }}
          dest: docs/sdks/python/reference
          artifact: bloock_lib_python-docs-${{ github.event.client_payload.version }}.zip
          post_script: scripts/generate-python-docs.js
